apiVersion: v1
data:
  app-config.yaml: |
    app:
      baseUrl: http://af70dc7e120184baf9783a8816b9334c-2038494241.us-east-1.elb.amazonaws.com
    backend:
      baseUrl: http://af70dc7e120184baf9783a8816b9334c-2038494241.us-east-1.elb.amazonaws.com
    techdocs:
      builder: 'local'
      generator:
        runIn: 'local'
      publisher:
        type: 'local'
kind: ConfigMap
metadata:
  name: my-release-backstage-app-config
  namespace: backstage
